FROM node:20-alpine

WORKDIR /backend

COPY . .

RUN yarn install --frozen-lockfile

COPY . .

RUN npx prisma generate

RUN yarn build

ENV NODE_ENV=production
EXPOSE 8080

CMD ["node", "dist/main.js"]
