FROM node:20-alpine

WORKDIR /backend

COPY backend/package.json backend/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY backend .

RUN npx prisma generate
RUN yarn build

ENV NODE_ENV=production
EXPOSE 8080

CMD ["node", "dist/main.js"]
