FROM node:20-alpine AS builder

WORKDIR /frontend

COPY frontend/package.json frontend/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY frontend .

RUN yarn build

FROM node:20-alpine

WORKDIR /frontend

COPY --from=builder /frontend ./

ENV NODE_ENV=production

EXPOSE 3000

CMD ["yarn", "start"]
