version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.front
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"

  backend-api:
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        RUN_PRISMA: ${RUN_PRISMA}
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:8080"

  postgres-dev:
    image: postgres:16
    container_name: postgres-dev
    profiles: ["dev"]
    environment:
      POSTGRES_DB: todos_dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_dev_data:
    driver: local
