version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.front
    environment:
      - NEXT_PUBLIC_API_URL=${BACKEND_API_URL}
    ports:
      - "3000:3000"

  backend-api:
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - postgres
    environment:
     - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
