FROM node:20-alpine AS builder

WORKDIR /frontend

COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci 

COPY frontend .

RUN npm run build

FROM node:20-alpine

WORKDIR /frontend

COPY --from=builder /frontend ./

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "start"]
