FROM node:20-alpine

WORKDIR /backend

COPY backend/package.json backend/package-lock.json ./
RUN npm ci --only=production

COPY backend .

RUN npx prisma generate
RUN npm run build

ENV NODE_ENV=production
EXPOSE 8080

CMD ["node", "dist/main.js"]
