#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git diff --cached --name-only | grep '^backend/'; then
  echo "🔍 Verificando backend..."
  cd backend
  yarn lint-staged
  yarn lint
  yarn test
fi

if git diff --cached --name-only | grep '^frontend/'; then
  echo "🔍 Verificando frontend..."
  cd frontend
  yarn lint-staged
  yarn lint
fi