name: Frontend CI/CD

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install

      # - name: Run tests
      #   working-directory: ./frontend
      #   run: yarn test

      - name: Build project
        working-directory: ./frontend
        run: yarn build && yarn export

      - name: Build Docker image
        run: docker build -t frontend:latest ./frontend

      - name: Login to EC2 via SSH and deploy frontend
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop frontend || true
            docker rm frontend || true
            docker pull frontend:latest || true
            docker build -t frontend:latest ./frontend
            docker run -d --name frontend -p 3000:3000 frontend:latest
